### ISSUE TITLE
Alpha channel is being ignored

### ISSUE THREAD

**Issue by tomires** [britzl/defold-png#1] opened 2018-04-29 10:27 UTC
![2018-04-27 15_24_47-tile navigator](https://user-images.githubusercontent.com/7209990/39405627-9a65a7a2-4ba8-11e8-8e22-0e98176f9b87.png)

![image](https://user-images.githubusercontent.com/7209990/39405625-924e5348-4ba8-11e8-90f1-00ab4356758b.png)

I have used the following snippet having changed only the game object URL and filename - https://github.com/britzl/defold-png#pngdecode_rgbabytes

Please see the following example to reproduce the bug:
[pngtest.zip](https://github.com/britzl/defold-png/files/1958646/pngtest.zip)

**Comment by britzl** [comment] 2018-04-29 17:35
Hmm, there must be something else going on. This should produce a 100x100 pixel image with all pixels red but fully transparent:

	local w = 100
	local h = 100
	local buf = buffer.create(w * h, {
		{
			name = hash("pixels"),
			type = buffer.VALUE_TYPE_UINT8,
			count = 4,
		}
	})

	local pixels = buffer.get_stream(buf, hash("pixels"))
	for x=0,w-1 do
		for y=0,h-1 do
			local i = y * w * 4 + x * 4 + 1
			local r = 255
			local g = 0
			local b = 0
			local a = 0
			pixels[i + 0] = r
			pixels[i + 1] = g
			pixels[i + 2] = b
			pixels[i + 3] = a
		end
	end

	local resource_path = go.get("#sprite", "texture0")
	local header = { width = w, height = h, type = resource.TEXTURE_TYPE_2D, format = resource.TEXTURE_FORMAT_RGBA, num_mip_maps = 1 }
	resource.set_texture(resource_path, header, buf)

The problem is that this results in a red image. Not sure what's wrong to be honest. Need to check with the engine devs.

**Comment by britzl** [comment] 2018-05-01 09:34
Fixed in: https://github.com/britzl/defold-png/releases/tag/1.2.0

You need to premultiply the alpha channel by passing in true as second argument to png.decode_rgba()

**Closed as completed by britzl** 2018-05-01 09:34 UTC

**Comment by tomires** [comment] 2018-05-01 10:25
Awesome, works a treat. Thanks!
